<?php

namespace AppBundle\Repository;

/**
 * CinemaShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CinemaShowRepository extends \Doctrine\ORM\EntityRepository
{
}
