<?php

namespace AppBundle\Repository;

/**
 * PriceCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
