<?php

namespace AppBundle\Repository;

/**
 * SeatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeatRepository extends \Doctrine\ORM\EntityRepository
{
}
