<?php

namespace AppBundle\Repository;

/**
 * SeatReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeatReservationRepository extends \Doctrine\ORM\EntityRepository
{
}
